#+TITLE: William Wear
#+OPTIONS: title:nil
#+MACRO: small @@html:<small>@@$1@@html:</small>@@

#+BEGIN_EXPORT html
<header class="site-header">
    <img src="logo.svg" alt="Logo" class="site-logo" />
    <h1 class="title">William Wear</h1>
</header>
#+END_EXPORT

Yes, I sometimes write essays that programmers keep asking to read, like [[file:quiet-art-of-attention.org][the quiet art of attention]].

Mostly, through, I write code, tests, doc, marketing content, help screens, and manpages.

Here's an example that took me about a day, dragging *APUE* along with me to the cafe:

 - [[file:hackers-ls.org][Hacker's ls CLI command]]: the code, the test rig, the build process, etc.
 - [[file:hackers-ls-tech-manual.org][hls(1) technical manual page]]: the user's manual page
 - [[file:hackers-ls-tech-mkt-content.html][tech marketing content for general use]]: a tech marketing blurb to be shaped into various marketing channels

There's actually more there at the [[https://github.com/billwear/hackers-cli][hacker's CLI repo]].

[[https://billwear.github.io/grep-oP-K-1.html][Here's an idea for a unique CLI video]] that talks about some little-known, underused options for grep that cut down on complex piping.

{{{small(Text passages copyright © 2026 by William Wear. All rights reserved. All code provided herein is free and unencumbered software released into the public domain under The Unlicense. For more information please refer directly to <https://unlicense.org/>.)}}}

