title: The Accidental Physicist
description: The physics of living
url: "https://billwear.github.io"
baseurl: ""

markdown: kramdown
permalink: /:year/:month/:day/:title/

# Build settings
exclude:
  - freezer/
  - README.md
  - LICENSE
  - "*.bak"

# RSS feed
plugins:
  - jekyll-feed
