title: DevRel & Tech Writer
description: Making systems legible to the people who need them
url: "https://billwear.github.io"
baseurl: ""

markdown: kramdown
permalink: /:year/:month/:day/:title/

# Build settings
exclude:
  - freezer/
  - README.md
  - LICENSE
  - "*.bak"

# RSS feed
plugins:
  - jekyll-feed
