title: bill wear
description: words, bits, cloth, silicon
url: https://billwear.github.io
theme: null
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# layout defaults
defaults:
  - scope: { path: "" }
    values:
      layout: single
      classes: wide
      author_profile: false

# navigation
minimal_mistakes_skin: default
paginate: 5
paginate_path: /page:num/
