.TH XDATE 1 "2026-05-15" "User Commands" "CLI-Improved Manual"
.SH NAME
xdate \- print a long date string to stdout.
.SH SYNOPSIS
.B xdate
[\fIOPTION\fR]...
.SH DESCRIPTION
\fBxdate\fR prints a long date string that includes the normal date output, the epoch number, and information about the days of the year. For example:
.PP
Sat May 16 13:04:20 CDT 2026, 1778954660; Day 136 of 365; 229 days remain.
.SH INSTALLATION
Copy the script from the GitHub repository to your $PATH, typically /usr/local/bin.
.SH AUTHOR
William Orian Wear (Bill Wear)
