.TH XMKDIR 1 "2026-05-15" "User Commands" "CLI-Improved Manual"
.SH NAME
xmkdir \- make directories with automatic creation of intermediate directories.
.SH SYNOPSIS
.B xmkdir
.I /directory/path/as/desired
.SH DESCRIPTION
\fBmkdir\fR creates a directory, including any non-existent intermediate directories included in the supplied pathname.  If the intermediate directories already exist, they are unchanged.
.SH INSTALLATION
Copy the script from the GitHub repository to your $PATH, typically /usr/local/bin.
.SH AUTHOR
William Orian Wear (Bill Wear)
