#+TITLE: THIS TERMINAL LIFE
#+AUTHOR: bill wear
#+DATE: Sat Jun 13 12:55:27 PM CDT 2026
#+OPTIONS: toc:nil num:nil

* This terminal life
We are all terminal.  And 99% of us pay taxes.

A somewhat lesser percentage of us work strictly at the computer
terminal, an arcane tool known as the *Command-Line Interface (CLI)*.

If CLI seems mysterious, you're not lost -- just follow the links that
are in *ALL CAPS* to stay away from the geekspeak.  I promise there's
plenty of stuff here for everyone, developer or not.

#+INCLUDE: "sitemap.org" :lines "3-"

** what's here, now?

This site encourages clear thinking, sharp focus, careful
decision-making, and wherever possible, plain living.  For those who
embrace CLI, I will be coding lots of tools to help; for those who
don't, the same tools are available for your favorite text editor,
though you might have to do a little more work.

There's also going to be a tutorial for those who want to learn CLI.
It takes time and patience, but it's honestly worth it.

Join me as we discover a rich life without filters and distractions.

